services:
  dev_water_demand_prediction:
    image: wdp_development:0.7
    mem_limit: "55g" # dein container darf maximal 55 GB RAM nutzen
    mem_reservation: "50g" # dein container sollte maximal 50GB RAM nutzen
    memswap_limit: -1  # dein container darf unbegrenzt swap nutzen (33GiB)
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    build: .
    container_name: development_wdp
    volumes:
      # Bind Data from outside the container to the container
      - "/home/jstueven/files:/service-water-demand-prediction/files/smartmeterdata"

      # Mount a volume to access trained models after container deletion
      - models_volume:/service-water-demand-prediction/files/trained_models
      - results_volume:/service-water-demand-prediction/files/results
    ports:
      - "8090:8080"
    networks:
      - flask-network
volumes:
  models_volume: #Done?#
  results_volume:
networks:
  flask-network:
    driver: bridge
