services:
  water-demand-prediction_name:
    image: image_water-demand-prediction:0.6
    build: .
    container_name: service-water-demand-prediction
    volumes: 
      - "/home/jstueven/files:/service-water-demand-prediction/files/smartmeterdata"
    ports:
      - "8090:8080"
    networks:
      - flask-network
networks:
  flask-network:
    driver: bridge
