openapi: 3.1.0
info:
  title: AutoARIMA Forecasts for Smart Meters
  version: "1.0"
  description: |
    This service enables users to create a forecast based on recorded smart
    meter data using the python AutoARIMA implementation pmdarima.

components:
  responses:
    RequestError:
      description: |
        Request Error

        Something you is wrong with your request. Please check the content of
        the response for more information
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ServiceError"

    ServerError:
      description: |
        Internal Service Error

        Something went wrong on the server during the handling of your request.
        Please check the response content for more information
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ServiceError"

  schemas:
    ServiceError:
      title: API Error
      description: >-
        This error schema is used by all microservices originating from the
        'wisdom-oss' GitHub organization. It is based on the RFC 9457 (Problem Details
        for HTTP APIs).
      type: object
      properties:
        type:
          type: string
          title: Error Type
          description: >-
            URI reference identifying the problem type. It may  point to an external
            resource, but this is not guaranteed
        status:
          type: integer
          title: HTTP Status Code
          description: >-
            The HTTP status code used in the response. This must match the http status
            set by the server.
          exclusiveMinimum: 0
        title:
          type: string
          title: Error Title
          description: This is the human readable title of the error
        detail:
          type: string
          title: Error Details
          description: This field may contain human readable details about the error
        instance:
          type: string
          title: Instance Name
          description: >-
            This field contains the instance of this error. This field might help
            identifying the request in the server logs
        errors:
          type: array
          title: Errors
          description: >-
            This field contains the errors generated on the server side to help with
            resolving issues.
          items:
            type: string
        host:
          type: string
          title: Host
          description: The host which generated the error response
      required:
        - type
        - status
        - title
        - host

    Datapoint:
      type: object
      properties:
        time:
          type: string
          format: date-time
        value:
          type: number
      required:
        - time
        - value

    ConfidenceDatapoint:
      type: object
      allOf:
        - $ref: "#/components/schemas/Datapoint"
        - properties:
            confidenceInterval:
              type: array
              minItems: 2
              maxItems: 2
              items:
                type: number
      required:
        - time
        - value
        - confidenceInterval

    Prediction:
      type: object
      properties:
        madeWithModel:
          type: string
          description: Contains the model id

    SmartMeter:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          format: uuid4
          nullable: false
        name:
          type: string
          nullable: false
        description:
          type: string
    TrainedModel:
      type: object
      properties:
        id:
          type: string
          format: uuid4
        meter:
          type: string
          format: uuid4
        hash:
          type: string
        comment:
          type: string
          nullable: True
        trainingStart:
          type: string
          format: date-time
        trainingDuration:
          type: string
          format: iso8601_duration
        dataStartsAt:
          type: string
          format: date-time
        dataEndsAt:
          type: string
          format: date-time
        weatherCapability:
          type: string
          enum:
            - air_temperature
            - precipitation
            - moisture
          nullable: True
        capabilityColumn:
          type: string
          nullable: True
paths:
  /meters:
    get:
      summary: List all available Smart Meters
      responses:
        "200":
          description: List of registered smart meters
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SmartMeter"

  /measured-data/{meter_id}:
    parameters:
      - in: path
        name: meter_id
        required: true
        schema:
          type: string

      - in: query
        name: bucket_size
        required: false
        description: |
          When using a `bucket_size` the timestamps of each bucket are moved
          to the end of the bucket, as this is the time the aggregation is
          correctly evaluated.
        schema:
          type: string
          format: duration
          description: |
            A ISO8601 duration string expressing the size of each bucket.

      - in: query
        name: start
        required: false
        description: |
          The point in time at which the list of returned data points should
          start. This value is inclusive (`date >= start`).
        schema:
          type: string
          format: date-time

      - in: query
        name: end
        required: false
        description: |
          The point in time at which the list of returned data points should
          end. This value is exclusive (`date < end`).
        schema:
          type: string
          format: date-time

    get:
      summary: Get Recorded Datapoints
      operationId: get_measured_data
      responses:
        "200":
          description: Recorded Data Points
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Datapoint"

        "4XX":
          $ref: "#/components/responses/RequestError"
        "5XX":
          $ref: "#/components/responses/ServerError"

  /training/start/{meter_id}:
    parameters:
      - in: path
        name: meter_id
        required: true
        schema:
          type: string

    put:
      summary: Initiate Training of Model
      description: |
        Initiate the training of a new model.

      parameters:
        - in: query
          name: startPoint
          required: false
          allowEmptyValue: false
          schema:
            type: string
            format: date-time
          description: |
            The starting point from which on the data for training the model
            should be taken from. If no value is sent, the service will use the
            first entry that appears in the database for the selected meter.

        - in: query
          name: timeSpan
          required: false
          allowEmptyValue: false
          schema:
            type: string
            format: duration
          description: |
            The size of the prediction expressed as a ISO8601 duration string

        - in: query
          name: weatherCapability
          required: false
          allowEmptyValue: false
          schema:
            type: string
            enum:
              - air_temperature
              - precipitation
              - moisture
          description: |
            The weather measurement that should provide exogenous variables for
            the training of the model

        - in: query
          name: weatherColumnName
          required: false
          allowEmptyValue: false
          schema:
            type: string
          description: |
            The column of the weather measurement that should be used as the
            exogenous variables for the ARIMA model training

      responses:
        "200":
          description: Started Model Training
          content:
            application/json:
              schema:
                type: object
                properties:
                  trainingId:
                    type: string

  /training/status/{training_id}:
    parameters:
      - in: path
        name: training_id
        required: true
        schema:
          type: string

    get:
      summary: Open WebSocket
      description: |
        Open a WebSocket connection to listen to the training progress of the
        specified training. The log is streamed as it is generated in the
        service and training.

      responses:
        "101":
          description: |
            Upgrade the connection to a WebSocket connection

  /models:
    get:
      summary: Get all trained models
      responses:
        "200":
          description: List of trained models
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TrainedModel"

  /models/{model_id}/training-data:
    get:
      summary: Get the data used for the training of the model
      responses:
        "200":
          description: "List of Datapoints used for the training of the model"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Datapoint"
