services:
  train_water_demand_prediction:
    image: wdp_training:0.7
    mem_limit: "55g" # dein container darf maximal 55 GB RAM nutzen
    mem_reservation: "50g" # dein container sollte maximal 50GB RAM nutzen
    memswap_limit: -1  # dein container darf unbegrenzt swap nutzen (33GiB)
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    build: .
    container_name: training_wdp
    volumes:
      # Bind Data from outside the container to the container
      - "/home/jstueven/files:/service-water-demand-prediction/files/smartmeterdata"

      # Mount a volume to access trained models after container deletion
      - models_volume:/service-water-demand-prediction/files/trained_models
    ports:
      - "9120:8080"
    networks:
      - flask-network
volumes:
  models_volume: #Done?
networks:
  flask-network:
    driver: bridge
